add_newline = true

format = """
$username\
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration
$character
"""

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold blue)"

[username]
style_user = "green bold"
style_root = "black bold red"
format = \uF303 [$user]($style) in"
show_always = true

[directory]
style = "bold cyan"
truncation_length = 3
truncate_to_repo = false

[git_branch]
symbol = "󰘬 "
style = "bold purple"

[git_status]
style = "bold yellow"

[cmd_duration]
min_time = 1000
format = "[󰔛 $duration]($style)"
style = "bold blue"

[fill]
symbol = " "
